# version: "3"

services:

  db:
    container_name: ShortURLDB
    build:
      context: ./db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:?err}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
      POSTGRES_USER: ${POSTGRES_USER:?err}
    healthcheck:
          test: [CMD-SHELL, "sh -c 'pg_isready -U ${POSTGRES_USER} --dbname ${POSTGRES_DB}'"]
          interval: 10s
          timeout: 5s
          retries: 5
    ports:
      - 5432:5432
    volumes:
      - postgresDB:/var/lib/postgresql/data
    networks:  
      - url_shortener_net


  app:
    container_name: ShortURLApi
    build: 
      context: ./app
    restart: always
    env_file: ./app/.env
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    networks:  
      - url_shortener_net


volumes:
 postgresDB:


networks:
  url_shortener_net:
